<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Ticket Messages Table Migration
     *
     * Stores chat messages within tickets.
     * Immutable - no edit/delete for audit trail.
     */
    public function up(): void
    {
        Schema::create('messages', function (Blueprint $table) {
            $table->id('message_id');

            $table->foreignId('ticket_id')
                ->constrained('tickets', 'ticket_id')
                ->onDelete('cascade');

            // Author of the message
            $table->foreignId('sender_id')
                ->constrained('users')
                ->onDelete('cascade');

            $table->text('body');

            // text   = written by a user or admin
            // system = auto-generated by the app (status changes, assignments, etc.)
            //          displayed in the chat as a human-readable event line
            $table->enum('type', ['text', 'system'])->default('text');

            // Immutable: only the creation timestamp is stored
            $table->timestamp('created_at')->useCurrent();

            $table->index('ticket_id');
            $table->index('sender_id');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('messages');
    }
};
