<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Ticket Messages Table Migration
     *
     * Stores chat messages within tickets.
     * Immutable - no edit/delete for audit trail.
     *
     * Columns match TicketService::addMessage() which writes:
     *   ticket_id, user_id, content, type
     */
    public function up(): void
    {
        Schema::create('ticket_messages', function (Blueprint $table) {
            $table->id();

            $table->foreignId('ticket_id')
                ->constrained('tickets')
                ->onDelete('cascade');

            // Author of the message
            $table->foreignId('user_id')
                ->constrained('users')
                ->onDelete('cascade');

            $table->text('content');

            // text   = written by a user or admin
            // system = auto-generated by the app (status changes, assignments, etc.)
            $table->enum('type', ['text', 'system'])->default('text');

            // Immutable: only the creation timestamp is stored
            $table->timestamp('created_at')->useCurrent();

            $table->index('ticket_id');
            $table->index('user_id');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ticket_messages');
    }
};
